sudo: required
dist: trusty

language: node_js

node_js:
  - '6.1'
  - '7.0'
  - '8.6'

cache:
  directories:
    - node_modules

services:
  - docker

env:
  global:
    - CC_TEST_REPORTER_ID=c705634424a58e3c1f0acdaf16dbfc688397458c6f62c765f3827bacc98a77eb

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install poppler-utils bash xfonts-75dpi xfonts-base
  - wget -q https://downloads.wkhtmltopdf.org/0.12/0.12.2.1/wkhtmltox-0.12.2.1_linux-trusty-amd64.deb
  - sudo dpkg -i wkhtmltox-0.12.2.1_linux-trusty-amd64.deb
  - "npm install -g mocha coffee-script ibrik codeclimate-test-reporter"
  - "npm install"
  - docker build -t pdf-service .
  - docker run -d -e USER='gooduser' -e PASS='secretpassword' -e PAYLOAD_LIMIT='50mb' -p 127.0.0.1:80:5555 --name pdf-service pdf-service
  - docker ps | grep -q pdf-service

after_script:
  - "npm run lint"
  - if [ $TRAVIS_BRANCH = 'master' ]; then ./cc-test-reporter after-build --coverage-input-type lcov coverage/lcov.info; fi
  - wget -O- https://toolbelt.heroku.com/install-ubuntu.sh | sh
  - heroku plugins:install heroku-container-registry
  - echo "machine api.heroku.com login ${HEROKU_EMAIL} password ${HEROKU_AUTH_TOKEN}" >> ${HOME}/.netrc
  - chmod 0600 ${HOME}/.netrc
  - docker login --email=_ --username=_ --password=$(heroku auth:token) registry.heroku.com
  - heroku container:push web --app docker-wkhtmltopdf-aas
