sudo: required
dist: trusty

language: node_js

services:
  - docker

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y poppler-utils bash npm
  - sudo npm install -g mocha coffee-script
  - sudo npm install chakram
  - docker build -t pdf-service .
  - docker run -d -e API_TOKEN='travisci' -p 127.0.0.1:80:5555 --name pdf-service pdf-service

script:
  - docker ps | grep -q pdf-service
  - mocha --compilers coffee:coffee-script/register test.coffee
